apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: stepigor/nodejsapp:arm
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nodejsapp-config
              key: DB_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejsapp-config
              key: APP_PORT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD