apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice-app
  template:
    metadata:
      labels:
        app: authservice-app
    spec:
      containers:
      - name: authservice-app
        image: stepigor/authserver:arm
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nodejsapp-config
              key: DB_HOST
        - name: AUTH_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejsapp-config
              key: AUTH_PORT
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD