apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: migrate
        image: postgres:15-alpine
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD
        command:
        - sh
        - -c
        - |
          psql -h postgresql.default.svc.cluster.local -U postgres -d users_db -c "
          CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL,
            age INT NOT NULL,
            password VARCHAR(60) NOT NULL
          );
          INSERT INTO users (name, email, age, password) VALUES
          ('Test User', 'test@example.com', 32, 'not hash')
          ON CONFLICT (email) DO NOTHING;
          "
      restartPolicy: OnFailure